<?php
/**
 *  @package     FrameworkOnFramework
 *  @subpackage  include
 *  @copyright   Copyright (C) 2010-2015 Nicholas K. Dionysopoulos
 *  @license     GNU General Public License version 2, or later
 *
 *  Initializes F0F
 */

defined('_JEXEC') or die();

if (!defined('F0F_INCLUDED'))
{
    define('F0F_INCLUDED', 'revAC17964');

    // -------------------------------------------------------------------------
    // Suppress PHP deprecation notices generated by F0F's own library files.
    //
    // F0F was written for PHP 5/7 and triggers E_DEPRECATED on PHP 8.x.
    // Because F0F uses a lazy autoloader, individual class files are parsed
    // (and their deprecations fired) long after this guard runs – on every
    // page request, not just during installation.
    //
    // We install a path-scoped error handler that:
    //  • silences any E_DEPRECATED / E_USER_DEPRECATED whose originating file
    //    lives inside F0F's own library directory, and
    //  • forwards every other error to whatever handler was already registered,
    //    so Joomla's own error handling is unaffected.
    //
    // The handler is installed once (inside the defined() guard) and remains
    // active for the life of the request, covering all lazily-autoloaded F0F
    // classes.
    // -------------------------------------------------------------------------
    $__f0f_path         = __DIR__ . DIRECTORY_SEPARATOR;
    $__f0f_prev_handler = set_error_handler(
        static function (
            int    $errno,
            string $errstr,
            string $errfile,
            int    $errline,
            array  $errcontext = []
        ) use ($__f0f_path, &$__f0f_prev_handler): bool {
            // Only intercept deprecation-class errors.
            if ($errno === E_DEPRECATED || $errno === E_USER_DEPRECATED) {
                // If the origin file is inside F0F's directory tree, suppress it.
                if (strpos($errfile, $__f0f_path) === 0) {
                    return true; // handled – PHP will not invoke any further handler
                }
            }
            // Forward everything else to whatever handler was previously active.
            if (is_callable($__f0f_prev_handler)) {
                return (bool) call_user_func(
                    $__f0f_prev_handler,
                    $errno, $errstr, $errfile, $errline, $errcontext
                );
            }
            // No previous custom handler – let PHP's built-in handler run.
            return false;
        },
        E_DEPRECATED | E_USER_DEPRECATED
    );
    // Clean up the outer-scope variables; the closure keeps both alive via reference.
    unset($__f0f_path, $__f0f_prev_handler);

	// Register the F0F autoloader
    require_once __DIR__ . '/autoloader/fof.php';
	F0FAutoloaderFof::init();

	// Register a debug log
	if (defined('JDEBUG') && JDEBUG)
	{
		// F0FPlatform::getInstance() may return null if no platform integration
		// is enabled (for example when this file is included before Joomla's
		// framework is fully loaded). Guard against that to avoid fatal errors.
		$fofPlatform = F0FPlatform::getInstance();
		if (is_object($fofPlatform)) {
			$fofPlatform->logAddLogger('fof.log.php');
		}
	}
}
